Ci machine fixup
bespoke-silicon-group/bsg_manycore pull request #547
Opened 2021-07-14 08:28 UTC by dpetrisko

- Removes deprecated BSG_MACHINE_BRANCH_TRACE_EN + BSG_MACHINE_VCACHE_MISS_FIFO_ELS
- BSG_MACHINE_X/Y_CORD_WIDTH ->  BSG_MACHINE_GLOBAL_X/Y_CORD_WIDTH (and actually connect it to testbench)
- Adds BSG_MACHINE_POD_X/Y_CORD_WIDTH
- Calculate subcord based on x/y_cord_width_p-pod_x/y_cord_width_p rather than `BSG_SAFE_CLOG2(num_tiles_x/y_p). This is more flexible because there are a variety of reasons one would want to keep the same (overprovisioned) coordinate size. For instance, accelerators with more tiles than manycore pods or software that may be written with a specific coordinate width in mind
- Reorganizes the machines/Makefile VCS_DEFINES list. I'm fine reverting this, but I moved it to match the Makefile.machine.include and it was much easier to verify everything was lined up that way, so I leave it to you

2021-07-14 17:20 UTC, taylor-bsg commented
Maybe add some comments somewhere that gives precise semantics of the added variables?

@drichmond BSG_MACHINE_VCACHE_MISS_FIFO_ELS is this the FIFO that controls the v-cache output fifo size? I think this is a feature that we determined had some non-trivial impact on performance, right?

2021-07-14 17:30 UTC, dpetrisko commented
>BSG_MACHINE_VCACHE_MISS_FIFO_ELS is this the FIFO that controls the v-cache output fifo size? I think this is a feature that we determined had some non-trivial impact on performance, right?

Is only used for non-blocking cache

2021-07-14 17:30 UTC, tommydcjung commented on v/bsg_manycore_tile_compute_ruche.v
> +    , parameter y_subcord_width_lp=y_cord_width_p-pod_y_cord_width_p
I think you want to calculate it the other way to avoid inconsistent input parameters.  pod_x_cord_width_p = x_cord_width_p-x_subcord_width_lp, where x_subcord_width_lp=`BSG_SAFE_CLOG2(num_tiles_x_p).

2021-07-14 17:30 UTC, tommydcjung requested changes
rc

2021-07-14 17:38 UTC, dpetrisko commented on v/bsg_manycore_tile_compute_ruche.v
> +    , parameter y_subcord_width_lp=y_cord_width_p-pod_y_cord_width_p
I believe decoupling the coordinate width from the number of tiles is better since:
- Manycore tile PD is identical for pods of different sizes. 
- Software written for pods of different sizes will be identical
- Changing the size of the manycore then does not change attached accelerator PD

2021-07-14 17:39 UTC, dpetrisko commented
>Maybe add some comments somewhere that gives precise semantics of the added variables?

Where's the best place to add this documentation @drichmond ?

2021-07-14 17:44 UTC, tommydcjung commented on v/bsg_manycore_tile_compute_ruche.v
> +    , parameter y_subcord_width_lp=y_cord_width_p-pod_y_cord_width_p
Manycore tile PD is not identical for pods of different sizes. For example. eva2npa mapping hardware will change. num_tiles_x/y_p determines the size of the pod, so it makes sense to have it derived from there.

2021-07-14 17:45 UTC, tommydcjung commented
> > Maybe add some comments somewhere that gives precise semantics of the added variables?
> 
> Where's the best place to add this documentation @drichmond ?

https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/machines/README.md

2021-07-14 17:49 UTC, taylor-bsg commented on v/bsg_manycore_tile_compute_ruche.v
> +    , parameter y_subcord_width_lp=y_cord_width_p-pod_y_cord_width_p
Yeah the pod would not be identical. But I think Dan is saying that we could have more stability in terms of the pinouts of the tile? So the PD flow could be more uniform?

2021-07-14 18:16 UTC, drichmond commented
> Maybe add some comments somewhere that gives precise semantics of the added variables?
> 
> @drichmond BSG_MACHINE_VCACHE_MISS_FIFO_ELS is this the FIFO that controls the v-cache output fifo size? I think this is a feature that we determined had some non-trivial impact on performance, right?

No - BSG_MACHINE_VCACHE_MISS_FIFO_ELS is for the non-blocking cache. IIRC it is the number of misses that can be absorbed from the network before back-pressuring the network. The response fifo depth that you're referring to is a different parameter that has never been PR'd (it is called BSG_MACHINE_VCACHE_RSP_FIFO_ELS).

I can add that in a PR. I rebased the branch containing it on Monday.

2021-07-14 18:17 UTC, drichmond commented
BSG_MACHINE_BRANCH_TRACE_EN was used to debug beebs, I think. Every time a branch was taken the core would spit out the result. I thought it was still hooked up as per some discussion in the manycore/tapeout meeting a couple months ago.

2021-07-14 18:20 UTC, tommydcjung commented
can we leave BSG_MACHINE_X/Y_CORD_WIDTH without changing its name? It will break the testbench tapeout repo and other places. Just document its meaning well in the README

2021-07-14 19:49 UTC, drichmond commented
It looks to me like BSG_MACHINE_BRANCH_TRACE_EN was removed from the top level testbench, and that may have been accidental. I don't think that means it was deprecated.

I recall a long conversation at one of the meetings about keeping it. I would prefer to keep it and we can file an issue to decide whether to remove it, and if not, have a test that verifies it still works.

2021-07-14 21:16 UTC, dpetrisko commented
>can we leave BSG_MACHINE_X/Y_CORD_WIDTH without changing its name? It will break the testbench tapeout repo and other places. Just document its meaning well in the README

Sure, no problem

2021-07-14 21:34 UTC, dpetrisko commented
>It looks to me like BSG_MACHINE_BRANCH_TRACE_EN was removed from the top level testbench, and that may have been accidental. I don't think that means it was deprecated.

#548

2021-07-14 21:44 UTC, dpetrisko commented on v/bsg_manycore_tile_compute_ruche.v
> +    , parameter y_subcord_width_lp=y_cord_width_p-pod_y_cord_width_p
identical->mostly identical. The TCL scripts can stay the same.

Basically, it has effects on things independent of the manycore pod itself. Notably accelerators + software.

2021-07-21 09:49 UTC, dpetrisko commented
How's this looking?

2021-08-03 20:50 UTC, dpetrisko commented
@mrutt92 relevant to the 4x2 config?

2021-08-03 21:00 UTC, mrutt92 commented
yeah, the ability to adjust pod_x/y_cord_width in the machine file is helpful for getting the 4x2 pod size to work.

2021-08-03 21:17 UTC, mrutt92 commented on v/bsg_manycore_tile_compute_ruche.v
> +    , parameter y_subcord_width_lp=y_cord_width_p-pod_y_cord_width_p
As someone who interacts with the RTL more than the PD, I think I support @tommydcjung's suggestion for the reasons he mentioned. 

But if there's merit to @dpetrisko's approach (tile cord width is calculated from the pod cord width and full cord width) most of the confusion over inconsistent parameter settings could be handled with an elaboration time assertion.

2021-08-03 21:30 UTC, dpetrisko commented on v/bsg_manycore_tile_compute_ruche.v
> +    , parameter y_subcord_width_lp=y_cord_width_p-pod_y_cord_width_p
It seems like if we are set on calculating subcord width, then we should remove
BSG_MACHINE_X_CORD_WIDTH, BSG_MACHINE_Y_CORD_WIDTH as parameters and calculate them as well since they serve no purpose. Otherwise, they will become inconsistent.

2021-08-03 22:10 UTC, tommydcjung commented on v/bsg_manycore_tile_compute_ruche.v
> +    , parameter y_subcord_width_lp=y_cord_width_p-pod_y_cord_width_p
I agree with having measures to prevent users from plugging inconsistent sets of parameters. In the context of manycore pod and this testbench (the source code you are modifying here), it is assumed that num_tiles in a pod determines the subcord width. I would say the user should be plugging in x/y_cord_width (global cord width), because that's the coordinate width in the network packet that is universal to the things connected to the manycore network. And you can calculate pod_x/y_cord as x/y_cord_width - subcord_x/y.

2021-08-03 23:42 UTC, dpetrisko commented on v/bsg_manycore_tile_compute_ruche.v
> +    , parameter y_subcord_width_lp=y_cord_width_p-pod_y_cord_width_p
Works for me, that will at least fix the bug this PR was intended for.

2021-08-04 01:39 UTC, tommydcjung approved these changes

2021-08-11 04:57 UTC, merged