Replacing parameters with localparams
bespoke-silicon-group/bsg_manycore pull request #606
Opened 2021-11-22 01:00 UTC by dpetrisko

Some tools (genus) and flows (ILM) like to have all parameters in name to resolve, otherwise subtle differences in instantiation can cause name mismatches. This causes all default parameters to be included in the name and makes the name extremely long and complex. For instance, the manycore tile actually breaks the filename length limit for Unix.

This PR replaces "localparameters" with localparam. In BP this also helped compile times significantly, but that's a secondary benefit. @taylor-bsg I don't think there are any tools we care about that can't handle localparams in module headers. Icarus Verilog is the only one I would guess, and there's no way the rest of bsg_manycore is going through that anyway

2021-11-22 01:37 UTC, taylor-bsg commented
Interesting -- how things have changed! So localparam in arguments is supported by DC, VCS, Surelog, Verilator, and Vivado?

2021-11-22 02:00 UTC, dpetrisko commented
And genus/xcelium ;)

BP uses them heavily, so if they weren’t supported it would have come up for anything we run BP through

2021-11-22 22:12 UTC, taylor-bsg commented
I think rather than placing lots of parameter keywords in many places, you can just use the parameter keyword in the next parameter after you add a localparam, to switch it back?

2021-11-22 22:46 UTC, dpetrisko commented
I like the explicitness of having the parameter keyword but it’s up to you. The error is very unintuitive, so not sure it’s worth the clarity hit for future maintainers

2021-11-23 10:04 UTC, dpetrisko commented
Think this is good to go once CI passes

2021-11-23 16:25 UTC, tommydcjung commented on v/bsg_cache_dma_to_wormhole.v
>    #(`BSG_INV_PARAM(vcache_addr_width_p)
missing "parameter" on the first ones.

2021-11-23 16:26 UTC, tommydcjung commented on v/bsg_manycore_hor_io_router.v
> +    , localparam int fwd_fifo_els_p[dims_lp*2:0] = '{2,2,2,2,2,2,2}
This is not localparam

2021-11-23 16:39 UTC, tommydcjung requested changes
Left feedback that must be addressed before merging.

2021-11-23 17:12 UTC, taylor-bsg commented
Yes, let's remove the redundant localparam and parameters. Unfortunately, it is things like this that kill our code size metrics versus other alternative HDL's (something that is particularly relevant for BlackParrot)

2021-11-23 18:29 UTC, dpetrisko commented on v/bsg_cache_dma_to_wormhole.v
>    #(`BSG_INV_PARAM(vcache_addr_width_p)
fixed

2021-11-23 18:29 UTC, dpetrisko commented on v/bsg_manycore_hor_io_router.v
> +    , localparam int fwd_fifo_els_p[dims_lp*2:0] = '{2,2,2,2,2,2,2}
good catch, this file isn't compiled normally so it wasn't caught

2021-11-23 19:21 UTC, tommydcjung commented on v/bsg_manycore_accel_default.v
>     #(`BSG_INV_PARAM(x_cord_width_p   )
There are all these first parameter in each module missing the keyword "parameter"

2021-11-23 20:28 UTC, dpetrisko commented on v/bsg_manycore_accel_default.v
>     #(`BSG_INV_PARAM(x_cord_width_p   )
technically, the first one isn't required because the list starts as parameter by default

2021-11-24 18:31 UTC, taylor-bsg commented on v/bsg_manycore_accel_default.v
>     #(`BSG_INV_PARAM(x_cord_width_p   )
I think it's okay to omit the first one. But can we go ahead and remove the redundant parameter and localparam statements? I still see a bunch in the code

2021-11-24 19:43 UTC, tommydcjung commented on v/bsg_manycore_accel_default.v
>     #(`BSG_INV_PARAM(x_cord_width_p   )
then we can remove parameter on the second one? Or put the parameter on the first one to be more clear.

2021-11-24 23:38 UTC, dpetrisko commented on v/bsg_manycore_accel_default.v
>     #(`BSG_INV_PARAM(x_cord_width_p   )
I just changed the parameter to localparam so no net change in keywords. If we want to code golf, we could have all parameters and then all localparams? Then it’s only 1 “localparam” per module

2021-11-29 13:33 UTC, dpetrisko commented on v/bsg_manycore_accel_default.v
>     #(`BSG_INV_PARAM(x_cord_width_p   )
@taylor-bsg Just pushed a version that's minified without grouping. I think anything further should be its own PR

2021-11-29 16:49 UTC, tommydcjung commented on v/bsg_manycore_tile_compute_array_ruche.v
>      // my_x/y_i
Can you also fix y/x_cord_width_p, pod_y/x_cord_width_p in this file?

2021-11-29 16:57 UTC, tommydcjung commented
these files are deprecated and no longer in use. These should be either reverted or deleted.
```
v/bsg_ruche_anti_buffer.v
v/bsg_manycore_rocc_wrapper.v
v/bsg_manycore_rocc_streambuf_wrapper.v
v/bsg_manycore_packet_streamer.v
v/bsg_manycore_mesh.v
v/bsg_manycore_links_to_fsb.v
v/bsg_manycore_link_to_rocc.v
```

2021-11-29 16:58 UTC, tommydcjung approved these changes

2021-11-30 02:01 UTC, dpetrisko commented on v/bsg_manycore_tile_compute_array_ruche.v
>      // my_x/y_i
fixed!

2021-11-30 02:01 UTC, dpetrisko commented
>these files are deprecated and no longer in use. These should be either reverted or deleted.

Reverted and added #609

2021-11-30 17:05 UTC, merged